[tools]
node = "latest"
"npm:@vscode/vsce" = "latest"
pnpm = "latest"

[tasks.setup]
run = "mise generate git-pre-commit --write --task=build"

[tasks.build]
run = """
./build.sh
"""

[tasks.publish]
depends = ["build"]
run = """
vsce publish
"""
